### ISSUE TITLE
command docker pull mcr.microsoft.com/dotnet/sdk:6.0 throwing error

### ISSUE THREAD

**Issue by Abhinav1598** [microsoft/containerregistry#112]
Error response from daemon: error parsing HTTP 400 response body: invalid character '<' looking for beginning of value: "

Our services aren't available right now
We're working to restore all services as soon as possible. Please check back soon.

00w1yYgAAAADr+GZP0awtS6P+4e4EaPC0TUFBMDJFREdFMDMxMQBFZGdl"
I am using openFaas to create a dotnet function, in the dockerfile pull for sdk:3.1 and runtime:3.1 is there and I am getting the above error.
other images are getting pulled but Microsoft ones are failing.

**Comment by AndreHamilton-MSFT** [comment]
@Abhinav1598  are you still experiencing this error

**Comment by AndreHamilton-MSFT** [comment]
Closing due to lack of response. Please feel free to reopen
