### ISSUE TITLE
Custom role - Unable to push to ACR

### ISSUE THREAD

**Issue by AmudaPalani** [microsoft/containerregistry#114]
Created this custom role. When this custom role is assigned to a User, User is able to create ACR, but unable to push images to it. Can you please fix this?

{
    "id": "xyz",
    "properties": {
        "roleName": "AAD-Eng_Admin",
        "description": "Role created to restirct Access to IAM and creation of Networking Components",
        "assignableScopes": [],
        "permissions": [
            {
                "actions": [
                    "Microsoft.Resources/subscriptions/resourceGroups/*",
                    "Microsoft.Network/routeTables/*",
                    "Microsoft.OperationsManagement/solutions/*",
                    "Microsoft.Authorization/locks/*",
                    **"Microsoft.ContainerRegistry/registries/*",**
                    "Microsoft.Authorization/roleAssignments/*",
                    "Microsoft.Automation/*",
                    "Microsoft.Compute/*",
                    "Microsoft.Storage/*",
                    "Microsoft.Resources/deployments/*",
                    "Microsoft.Sql/*",
                    "Microsoft.KeyVault/*",
                    "Microsoft.DevTestLab/*",
                    "Microsoft.Support/*",
                    "Microsoft.Insights/*",
                    "Microsoft.OperationalInsights/*",
                    "Microsoft.ContainerService/*",
                    "Microsoft.Kubernetes/*",
                    "Microsoft.ServiceBus/*",
                    "Microsoft.DataLakeAnalytics/*",
                    "Microsoft.DesktopVirtualization/*",
                    "Microsoft.SerialConsole/*",
                    "Microsoft.SqlVirtualMachine/*",
                    "Microsoft.Web/*",
                    "Microsoft.RecoveryServices/*",
                    "Microsoft.DataProtection/*",
                    "Microsoft.DocumentDb/*",
                    "Microsoft.Network/applicationGateways/backendAddressPools/join/action",
                    "Microsoft.Network/loadBalancers/backendAddressPools/join/action",
                    "Microsoft.Network/loadBalancers/inboundNatPools/join/action",
                    "Microsoft.Network/loadBalancers/inboundNatRules/join/action",
                    "Microsoft.Network/loadBalancers/probes/join/action",
                    "Microsoft.Network/locations/*",
                    "Microsoft.Network/networkInterfaces/*",
                    "Microsoft.Network/networkSecurityGroups/*",
                    "Microsoft.Network/publicIPAddresses/join/action",
                    "Microsoft.Network/virtualNetworks/subnets/*",
                    "Microsoft.Network/virtualNetworks/join/action",
                    "Microsoft.Network/virtualNetworks/subnets/joinViaServiceEndpoint/action",
                    "Microsoft.Network/dnsZones/*",
                    "Microsoft.Network/privateDnsZones/*",
                    "Microsoft.Network/privateDnsOperationResults/*",
                    "Microsoft.Network/privateDnsOperationStatuses/*",
                    "Microsoft.DataLakeAnalytics/accounts/*",
                    "Microsoft.Synapse/*",
                    "Microsoft.Network/loadBalancers/write",
                    "Microsoft.Network/applicationGateways/write",
                    "Microsoft.Network/applicationGateways/backendhealth/action",
                    "Microsoft.Network/privateEndpoints/*",
                    "*/read"
                ],
                "notActions": [],
                "dataActions": [],
                "notDataActions": []
            }
        ]
    }
}

**Comment by AmudaPalani** [comment]
Adding these permissions to above role, we are able to workaround this bug:

        "Microsoft.ContainerRegistry/registries/pull/read",
        "Microsoft.ContainerRegistry/registries/push/write"
        
 But question remains, why we need to add this when we have "Microsoft.ContainerRegistry/registries/*" permission

**Comment by AndreHamilton-MSFT** [comment]
Closing due to age. This repository is for issues with mcr.microsoft.com . You can file issues with acr on https://github.com/Azure/acr/issues
