### ISSUE TITLE
Fatal error with mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest

### ISSUE THREAD

**Issue by dfibuch** [microsoft/containerregistry#115]
We've been using the Linux azure-cosmos-emulator for few months now and came across an issue today when I rebuilt my local docker images. Pulling the `latest` image (1.93 GB) starts up the container but immediately shows these errors and the instances shuts down

![image](https://user-images.githubusercontent.com/4235431/169045306-b007b7fd-cc59-44f9-953c-2a931ad8a7fd.png)

If I change the tag to say "2.14.5.2" (2.21 GB) everything works fine

![image](https://user-images.githubusercontent.com/4235431/169045569-7c854b53-4fee-4008-ad03-1b5f7bc6697d.png)

Don't know if this is the right place to raise this issue so please move/link accordingly.

**Comment by AndreHamilton-MSFT** [comment]
This repository is for mcr.microsoft.com issue. File issues related to cosmosdb emulator https://github.com/Azure/azure-cosmos-db-emulator-docker/issues
