### ISSUE TITLE
Certificate Issue

### ISSUE THREAD

**Issue by anthonyhollings** [microsoft/containerregistry#12]
When I try to pull a docker image from MCR I get the following error.

```
sudo docker pull mcr.microsoft.com/dotnet/core/aspnet:2.2.7-bionic
Error response from daemon: Get https://mcr.microsoft.com/v2/: x509: certificate is valid for *.mcr.microsoft.com, not mcr.microsoft.com
```

**Comment by spBrianWerth** [comment]
Same

**Comment by connorearl** [comment]
I am also experiencing this issue

**Comment by connorearl** [comment]
Looks like it's working now

**Comment by spBrianWerth** [comment]
Also working here, thanks Microsoft!

**Comment by anthonyhollings** [comment]
Working now here too

**Comment by bariscaglar** [comment]
In case anyone here is wondering, we had an outage due to a deployment error. Thank you for your patience. It should all be back to normal now.
