### ISSUE TITLE
MCR URLs are unintuitive, effectively app not registry based

### ISSUE THREAD

**Issue by richlander** [microsoft/containerregistry#120]
This URL fails: https://mcr.microsoft.com/product/dotnet/sdk
This URL works: https://mcr.microsoft.com/product/dotnet/sdk/about

It's very odd to share MCR URLs to other parties with `about` in them. It's also a strange compatibility burden for you to carry. Everything after `product` should be registry concepts, at least in terms of required data.

Please make the first URL work.

**Comment by terencet-dev** [comment]
Hi @richlander, 

Thanks for sending this over. I am tagging this as a Feature Request and will add this item to our backlog. Will provide updates whenever I get them from our team. Thanks!

**Comment by AndreHamilton-MSFT** [comment]
@richlander the first url now works
