### ISSUE TITLE
eastasia.data.mcr.microsoft.com ssl certificate has expired

### ISSUE THREAD

**Issue by Adam-Jin** [microsoft/containerregistry#121]
## eastasia.data.mcr.microsoft.com ssl certificate has expired
![image](https://user-images.githubusercontent.com/20434035/176991287-b6f9b334-3e67-41f5-8165-b04364954859.png)
![image](https://user-images.githubusercontent.com/20434035/176991302-108a6ad7-910e-46d7-a022-903be855c50b.png)

**Comment by richlander** [comment]
An ICM issue has been created: https://portal.microsofticm.com/imp/v3/incidents/details/317995586/home (MS internal link).

**Comment by AndreHamilton-MSFT** [comment]
Issue was mitigated around 10:20am pst. Please let us know if you continue to see issues
