### ISSUE TITLE
Registry and Data Endpoint IP addresses

### ISSUE THREAD

**Issue by robertofan** [microsoft/containerregistry#126]
Is it possible to have the list of the IP addresses that need to be enabled on firewalls/proxies for content discovery and delivery?
I am referring to the IP addresses behind the endpoints published on [Microsoft Artifact Registry (MAR) Client Firewall Rules Configuration](https://github.com/microsoft/containerregistry/blob/main/client-firewall-rules.md):
- mcr.microsoft.com
- *.data.mcr.microsoft.com

I see that these addresses are not included in the list of the Microsoft 365 URLs and IPs ranges, published and maintained on [Office 365 URLs and IP address ranges
](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)

I am asking because some firewalls don’t allow configurations with FQDNs and the complete list of IP addresses is needed.

**Comment by AndreHamilton-MSFT** [comment]
@robertofan Please see guidance about azure service tags(https://learn.microsoft.com/en-us/azure/container-registry/container-registry-firewall-access-rules#allow-access-by-ip-address-range), which includes how you can use the service tag file to map a tag to a given ip range. **Pay special attention to the warning that ip address ranges can and will change**. You can use the [Service Tag Overview](https://learn.microsoft.com/en-us/azure/virtual-network/service-tags-overview) to see the  MicrosoftContainerRegistry tag which has a dependency you need to include.
