### ISSUE TITLE
kubernetes security patch needs to be done

### ISSUE THREAD

**Issue by kaymenji** [microsoft/containerregistry#129]
Hi there,

Can you please kindly apply security patch to NPE AKS mazcaecbunpeceaks01? 

Please find attached the prisma alert list. 

If you want to contact me, email : kaymen.ji@rci.rogers.com

[mazcaecbunpeceaks01_microsoft.xlsx](https://github.com/microsoft/containerregistry/files/10014314/mazcaecbunpeceaks01_microsoft.xlsx)

**Comment by AndreHamilton-MSFT** [comment]
Closing due to age. Also please forward aks support request to https://github.com/Azure/AKS
