### ISSUE TITLE
MAR Image Name Sorting

### ISSUE THREAD

**Issue by RichardMuniu** [microsoft/containerregistry#133]
At a glance, the default listing for image tags on the official website does not seem to have any particular sorting order. It is, however, possible to sort container images and manifest lists by name. Again, it seems at a glance that this sorting is alphabetical, which is rather counterintuitive and ineffective for tags (which make up the name field) since it completely ignores semantic versioning. 

For instance, in a sort, a tag such as "v1.0.10" would show up next to "v1.0.1", although a "v1.0.9" exists. This makes it very difficult to figure out what the latest available tag is in such cases. 

Is it possible to rank images using SemVer rather than their alphabetical names?

**Comment by AndreHamilton-MSFT** [comment]
Unfortunately, not all tags follow semversion so this would result in some oddities in sroting. We are working to improve tag finding
