### ISSUE TITLE
Certificate error when I try to pull a docker image from MCR I get the following error.

### ISSUE THREAD

**Issue by shravanipatil527** [microsoft/containerregistry#142]
error pulling image configuration: Get "https://mcr.microsoft.com/v2/dotnet/core/sdk/blobs/sha256:2357b6790b9df0fb28364d113ff94eb67628cb1564aa86074d24c68b1597b62e": x509: certificate is valid for *.azureedge.net, *.media.microsoftstream.com, *.origin.mediaservices.windows.net, *.streaming.mediaservices.windows.net, not mcr.microsoft.com

**Comment by AndreHamilton-MSFT** [comment]
@shravanipatil527 is this still occuring for you? is this happening frequently? are you able to provide a network trace?

**Comment by AndreHamilton-MSFT** [comment]
@shravanipatil527 I will close this as we have not heard back from you but if you see anymore please free to reopen
