### ISSUE TITLE
No Information Regarding Supply Chain Validation of Containers 

### ISSUE THREAD

**Issue by shin-san** [microsoft/containerregistry#143]
Hi Team,

I could not find any documentation regarding signature validation of containers, specifically `mcr.microsoft.com/mssql/rhel/server` images.

This can be problematic as this can be an issue for a cluster or container platform that enforces supply chain security validation.

It would be much appreciated to understand which GPG keys to use and the sigstore URL location, or if the images are signed using sigstore cosign stack.

**Comment by shin-san** [comment]
Thanks for the update, @johnsonshi. Do we have a timeframe on when can we expect the image signing to take effect?

Will there be some backwards compatibility with cosign if that is the preferred method of signature signing and validation?

**Comment by AndreHamilton-MSFT** [comment]
cc @johnsonshi for updates

**Comment by johnsonshi** [comment]
Unfortunately, we do not have a clear timeline for all `mcr.microsoft.com` images to have either Notation-based or cosign-based signature validation.
