### ISSUE TITLE
private endpoint ACR: Does this create a new VNet?

### ISSUE THREAD

**Issue by AmudaPalani** [microsoft/containerregistry#147]
We are using a network overlay and our VNets are configured with it. Due to this, we have an Azure policy to restrict new VNet creation. But recently from Azure portal when we create a new ACR with private endpoint to an existing VNet, it's throwing a policy violation error "VNet creation is not allowed".

Can you please clarify why is creating a new ACR with private endpoint, creating a new VNet?

Note: We have had this policy for more than a year, creation of new ACR with private endpoint was working fine before.

**Comment by AndreHamilton-MSFT** [comment]
Please file issues related to acr https://github.com/Azure/acr as this github is for issues related to mcr.microsoft.com
