### ISSUE TITLE
Check whether the file has been patched update

### ISSUE THREAD

**Issue by winnie008** [microsoft/containerregistry#154]
Hi team,

We notice there is an updated image “4.7.2-20231114-windowsservercore-ltsc2019” from the doc (https://[hub.docker.com](https://hub.docker.com/_/microsoft-dotnet-framework-runtime/)/_/microsoft-dotnet-framework-runtime/), however, this image is still detected vulnerability finding "Microsoft .NET Framework Update for November 2023" in Microsoft Defender for Cloud.

Could you please verify whether the base file has been patched update?

Thanks for your help!

**Comment by winnie008** [comment]
Hi team, are there any updates?

**Comment by AndreHamilton-MSFT** [comment]
There are now more updated images available for windows server core. Please see images listed https://mcr.microsoft.com/en-us/product/dotnet/framework/runtime/tags
