### ISSUE TITLE
Is the MCR suitable for internal-only tools?

### ISSUE THREAD

**Issue by chris-tomich-msft** [microsoft/containerregistry#155]
Hi, I'm part of a team within Microsoft and we're wondering if the MCR is suitable for hosting our VS Code extension. The extension is for internal use only so we'd only want it available to people logged in on a Microsoft account.

If we are able to publish internal only tools to the MCR, do you have any onboarding information?

**Comment by AndreHamilton-MSFT** [comment]
Provided documents internally
