### ISSUE TITLE
southeastasia.data.mcr.microsoft.com Certificate has expired

### ISSUE THREAD

**Issue by zhj-hx** [microsoft/containerregistry#156]
[https://github.com/microsoft/containerregistry/issues/121](url)
I encountered similar problem
![企业微信截图_a4c28b9c-34fa-4bb8-a167-98a24ee15a5d](https://github.com/microsoft/containerregistry/assets/81075106/04c39eeb-5450-4c44-b9d9-78b6a290f908)

**Comment by AndreHamilton-MSFT** [comment]
@zhj-hx thanks for reaching out. We caught the issue and updated the certificates. Let us know if you are still seeing the issue

**Comment by zhj-hx** [comment]
Thank you, it's back to normal
