### ISSUE TITLE
Cant pull Microsoft runtime images : 503 Service Unavailable

### ISSUE THREAD

**Issue by ksrivastav** [microsoft/containerregistry#157]
I am trying to pull Microsoft runtime images and receiving   503 Service Unavailable. 
**Commands on which error is received** 
1. docker pull mcr.microsoft.com/dotnet/aspnet:8.0
2. docker pull mcr.microsoft.com/dotnet/sdk:8.0

**Error Received** 
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable

**Comment by oriser** [comment]
Same here for `mcr.microsoft.com/playwright/python:v1.40.0-jammy`

**Comment by ggiesen** [comment]
Same here for `mcr.microsoft.com/powershell:latest`

**Comment by kyleli666** [comment]
Same here for dotnet, we temporarily change "mcr.microsoft.com/dotnet" to "registry.cn-hangzhou.aliyuncs.com/newbe36524"...
It was working early this morning around 10AM(UTC+8), then it replies with 401 Unauthorized, and finally 503 Unavailable.

**Comment by moo-the-cow** [comment]
confirmed from EU

**Comment by emrys90** [comment]
Same here for `mcr.microsoft.com/dotnet/sdk:8.0`

**Comment by oriser** [comment]
Looks like it resolved

**Comment by AndreHamilton-MSFT** [comment]
@Ganesh1991 can you share what region you are in. Is this still ongoing? We are currently investigating some issues impacting azure jio india west and working on mitigation

**Comment by AndreHamilton-MSFT** [comment]
@ksrivastav and for other users. The outage on this date is linked to this specific azure incident https://azure.status.microsoft/status/history/?trackingId=NKRF-1TG

**Comment by theofred** [comment]
Had problems creating a devcontainer based on `mcr.microsoft.com/devcontainers/dotnet:1-6.0` from Germany right now.

Used VPN to connect to New York and it worked just fine.

**Comment by AndreHamilton-MSFT** [comment]
@ksrivastav closing since ive linked the appropriate outage.
