### ISSUE TITLE
I cannot see the image published in MCR

### ISSUE THREAD

**Issue by DaweiCai** [microsoft/containerregistry#161]
We are from Azure AI Platform team. We have published one image to MCR. It can be pulled successfully and we can use below request to get the tags: https://mcr.microsoft.com/v2/azureml/promptflow/promptflow-runtime/tags/list. But we can not see the image in mcr protal: https://mcr.microsoft.com/.

Do you know the reason or did we miss some steps?

**Comment by AndreHamilton-MSFT** [comment]
Spoke offline.
