### ISSUE TITLE
Why can't I find existing image on MCR site?

### ISSUE THREAD

**Issue by saikotek** [microsoft/containerregistry#163]
Hello,
I wanted to check versions/tags of mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator image so I went to https://mcr.microsoft.com/ but I can't find that image listed on site at all.

**Comment by AndreHamilton-MSFT** [comment]
It is up to individual teams to make their content available on mcr.microsoft.com. You can always use the tags api to get the list of available tags https://mcr.microsoft.com/v2/cosmosdb/linux/azure-cosmos-emulator/tags/list
