### ISSUE TITLE
MCR too slow in Costa Rica

### ISSUE THREAD

**Issue by darkguy2008** [microsoft/containerregistry#30]
Okay so I've went through a lot of struggle with different ISPs here (had to move to a new home, so that's why) and no matter the ISP, downloading from mcr.microsoft.com is an ordeal.

This is going at around 200Kb/s (and my FTTH is 100/100mbps...):

![image](https://user-images.githubusercontent.com/6304136/88845666-b97ae400-d1a1-11ea-9acd-94558adaa700.png)

Or even less, watch the graph below:

![image](https://user-images.githubusercontent.com/6304136/88845713-ca2b5a00-d1a1-11ea-85c3-f85ce7213fc1.png)

Ping just hangs there:

![image](https://user-images.githubusercontent.com/6304136/88845798-ee873680-d1a1-11ea-8299-eebd294c6ced.png)

Speedtest shows a different story though (I'm capped at 50mb/s due to my current network devices in-between):

![image](https://user-images.githubusercontent.com/6304136/88846294-addbed00-d1a2-11ea-94e3-2f303dbc0f7b.png)

Same for Fast.com:

![image](https://user-images.githubusercontent.com/6304136/88846337-be8c6300-d1a2-11ea-97bf-bb8165523ea0.png)

So, I read somewhere here that the idea of creating mcr.microsoft.com was for it to be the trusted source for docker container images from Microsoft. However, **reliability** is included in **trust**, and unfortunately that decision makes MCR very **unreliable** in this side of the world, therefore I can't just trust MCR. I need something better. A mirror would be a good idea, or fix the central server if you don't want to make mirrors, but these speeds are just ridiculous.

Any ideas are appreciated, this is really hampering my development speed and reliability on my side because all I can do is just sit down and wait until the images finish downloading without any other alternative (like Docker Hub, which works flawlessly).

**Comment by bariscaglar** [comment]
@darkguy2008 my apologies for the late response. We will ensure that these voices are heard in a more timely manner in the future. The issue you created fell between the cracks due to an inadequacy in our process. While we are fixing our process, I am curious if this is still happening for you. Central America has not been a region we have received complaints about before. While pulling image layers as in your screenshot, you are working with the CDN, which might have to retrieve these images from a distant backend. If you are still observing this, we can try to pinpoint where the problem is and try to remediate.

**Comment by jmoeyersons** [comment]
Same issue in Belgium, the downloads of the different layers are very slow (when working with the visual studio dev containers)

**Comment by bariscaglar** [comment]
@jmoeyersons do you still seeing issues? From time to time we encounter these slow downs, but they should eventually get resolved.

**Comment by darkguy2008** [comment]
> @darkguy2008 my apologies for the late response. We will ensure that these voices are heard in a more timely manner in the future. The issue you created fell between the cracks due to an inadequacy in our process. While we are fixing our process, I am curious if this is still happening for you. Central America has not been a region we have received complaints about before. While pulling image layers as in your screenshot, you are working with the CDN, which might have to retrieve these images from a distant backend. If you are still observing this, we can try to pinpoint where the problem is and try to remediate.

No problem Baris, thanks a lot for your response, it's greatly appreciated.

Maybe after a month or two after I made this issue, it seems to have been resolved on its own. I don't really know what would have been the reasons as I'm still using the same ISP, but yeah that's what I imagined, some issue with the CDN being outdated (?) and pulling the images from a distant backend. 

I tried again some days ago and it worked fine, so I guess this issue could be closed - although they sometimes to last days or even weeks, so it's surely something to look into.

**Comment by bariscaglar** [comment]
Great! Thanks for letting us know. @jmoeyersons if you're still seeing issues in Belgium please file a new issue!

**Comment by jmoeyersons** [comment]
@bariscaglar Thank you for your comment. The downloads already happens a lot faster by now (not yet on max speed I think), but it is much more comfortable to work with.
No need for a new issue at the moment 😉
