### ISSUE TITLE
Is the microsoft container registry subject to dockerhub throttling?

### ISSUE THREAD

**Issue by sparrc** [microsoft/containerregistry#38]
Hello, as you probably know, [dockerhub has recently begun throttling pulls](https://www.docker.com/increase-rate-limits?utm_source=docker&utm_medium=web%20referral&utm_campaign=pull%20limits%20hub%20home%20page&utm_budget=).

Since the microsoft container registry has it's "discovery mechanism" through dockerhub, will it be subjected to dockerhub throttling? I mainly ask because it seems that the rate-limiting applies to pulling manifests from dockerhub, not just the image itself.

**Comment by bariscaglar** [comment]
As long as images are pulled through mcr.microsoft.com, they are not subject to throttling.
