### ISSUE TITLE
Question: Is There a Way to Get Notify/Email/Webhook If Offical Image is Updated?

### ISSUE THREAD

**Issue by MichaelSimons** [microsoft/containerregistry#4]
@denhsu commented on [Thu Jul 04 2019](https://github.com/microsoft/aspnet-docker/issues/187)

We have our application image store in Azure Container Registry and it uses Microsoft official image "microsoft/aspnet:4.7.1-windowsservercore-ltsc2016".

Is it possible to notify us/email/webhook when image is updated in this repo?  For example, automatically trigger a build in our Azure DevOps to rebuild the application to take latest OS image.

Thanks!

---

@MichaelSimons commented on [Tue Jul 09 2019](https://github.com/microsoft/aspnet-docker/issues/187#issuecomment-509723994)

I am not aware of anything.  If you are able to utilize ACR Tasks, they have support for this scenario as described [here](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-overview#automate-os-and-framework-patching).

Moving to https://github.com/microsoft/ContainerRegistry since this is an MCR specific question.

**Comment by SteveLasker** [comment]
https://aka.ms/acr/tasks is our supported scenario.
We had hoped to get this enabled with Docker Hub, however we haven't had an update from Docker on this item.

**Comment by SteveLasker** [comment]
@denhsu
Closing, in-lieu of an update from docker hub.
To make a request for more generic notifications, please submit a request to https://aka.ms/acr/uservoice 
While I realize this is under ACR, we track both issues here.
