### ISSUE TITLE
Builds for arm64

### ISSUE THREAD

**Issue by moredhel** [microsoft/containerregistry#40]
As arm machines are becoming more popular (mostly due to the new apple silicon machines), it would be beneficial to start building arm64 images for both these & the new arm64 raspberry pi's.

**Comment by bariscaglar** [comment]
Thank you for your suggestion, but MCR does not build these images as it is only the distribution mechanism. I would recommend reaching out to the owners of the specific images for which you would like to see ARM distributions.
