### ISSUE TITLE
Cannot pull some of the Nanoserver and WindowsServerCore image tags

### ISSUE THREAD

**Issue by dbramhallconcentrix** [microsoft/containerregistry#5]
When I try to download a lot of the  Windows Server Core and Nano Server images, I get the below error. 

**Error**
Error response from daemon: manifest for microsoft/windowsservercore:latest not found.

Same issue with mcr.microsoft.com images/tags

**Same issue as the below**
https://github.com/docker/for-win/issues/3761

![Docker About](https://user-images.githubusercontent.com/52007100/61639135-1f13c680-ac58-11e9-9846-cf53bd173d6a.png)

**Comment by rotata** [comment]
could you please provide some diagnostic logs for your issue, you can find more information on the steps to get the logs here https://docs.microsoft.com/en-us/azure/container-registry/container-registry-faq#enable-and-get-the-debug-logs-of-the-docker-daemon.
Also, how many images are you trying to download?

**Comment by dbramhallconcentrix** [comment]
I am just trying to run a docker pull command to pull specific tags for the Nanoserver and Windows Server Core tags. Why do you need diagnostic logs for this? Can you verify that all the tags provided in the below links are available? A lot of my colleagues are experiencing the same issue.

Nano Server Images
https://hub.docker.com/_/microsoft-windows-nanoserver


Windows Server Core Images
https://hub.docker.com/_/microsoft-windows-servercore-insider


[CNX_logo_Color_SMALL]
Dena Bramhall | Sr. DevOps Engineer
201 East Fourth Street Cincinnati OH 45202
m: +1 719-393-5115
Dena.Bramhall@concentrix.com
www.concentrix.com<http://www.concentrix.com/>

**Comment by bariscaglar** [comment]
I have tried a few of them (1903, 1903-KB4505057, 1809) from nanoserver and all three worked. Which tags are you having trouble with?

**Comment by bariscaglar** [comment]
If you're trying "latest" tag, it won't work because the Windows team decided to discontinue that tag due to ambiguity it carried. You'll see that it doesn't exist in the full tag listing. This [article](https://techcommunity.microsoft.com/t5/Containers/Windows-Server-2019-Now-Available/ba-p/382430)has more on that.

**Comment by dbramhallconcentrix** [comment]
Yep, I saw the article about no more latest. I am not trying to pull latest tags for any MS docker images. Below is an image of the tags I tried today.

[cid:image001.png@01D54165.FFACE180]

[CNX_logo_Color_SMALL]
Dena Bramhall | Sr. DevOps Engineer
201 East Fourth Street Cincinnati OH 45202
m: +1 719-393-5115
Dena.Bramhall@concentrix.com
www.concentrix.com<http://www.concentrix.com/>

**Comment by bariscaglar** [comment]
I'm sorry, I don't think your image uploaded correctly. This is all I am seeing:

Yep, I saw the article about no more latest. I am not trying to pull latest tags for any MS docker images. Below is an image of the tags I tried today.

[cid:image001.png@01D54165.FFACE180]

**Comment by dbramhallconcentrix** [comment]
I have attached a .png file

[CNX_logo_Color_SMALL]
Dena Bramhall | Sr. DevOps Engineer
201 East Fourth Street Cincinnati OH 45202
m: +1 719-393-5115
Dena.Bramhall@concentrix.com
www.concentrix.com<http://www.concentrix.com/>

**Comment by mamezgeb** [comment]
Hi there, we on the GitHub issue page can't see the image you're attaching. Could you use the GitHub issue UI [here](https://github.com/microsoft/containerregistry/issues/5) and attach the image using the comment system? Or alternatively, list out the tags that are failing? I'm in alignment with Baris' prior comments.

**Comment by dbramhallconcentrix** [comment]
PS C:\Windows\system32> docker pull mcr.microsoft.com/windows/servercore:1809
1809: Pulling from windows/servercore
no matching manifest for unknown in the manifest list entries
PS C:\Windows\system32> docker pull mcr.microsoft.com/windows/nanoserver:1809
1809: Pulling from windows/nanoserver
no matching manifest for unknown in the manifest list entries
PS C:\Windows\system32> docker pull mcr.microsoft.com/windows/servercore:ltsc2019
ltsc2019: Pulling from windows/servercore
no matching manifest for unknown in the manifest list entries
PS C:\Windows\system32> docker run mcr.microsoft.com/windows/nanoserver:1903
Unable to find image 'mcr.microsoft.com/windows/nanoserver:1903' locally
1903: Pulling from windows/nanoserver
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: no matching manifest for unknown in the manifest list entries.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
PS C:\Windows\system32> docker pull mcr.microsoft.com/windows/servercore/insider:10.0.18932.1000
10.0.18932.1000: Pulling from windows/servercore/insider
no matching manifest for unknown in the manifest list entries
PS C:\Windows\system32> docker pull mcr.microsoft.com/windows/servercore/insider
Using default tag: latest
Error response from daemon: manifest for mcr.microsoft.com/windows/servercore/insider:latest not found

[CNX_logo_Color_SMALL]
Dena Bramhall | Sr. DevOps Engineer
201 East Fourth Street Cincinnati OH 45202
m: +1 719-393-5115
Dena.Bramhall@concentrix.com
www.concentrix.com<http://www.concentrix.com/>

**Comment by mamezgeb** [comment]
When you run `docker info`, what shows up by `Kernel Version' and `Operating System`?

**Comment by dbramhallconcentrix** [comment]
Client: Docker Engine - Community
Version:           18.09.2
API version:       1.39
Go version:        go1.10.8
Git commit:        6247962
Built:             Sun Feb 10 04:12:31 2019
OS/Arch:           windows/amd64
Experimental:      false

Server: Docker Engine - Community
Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     false

[CNX_logo_Color_SMALL]
Dena Bramhall | Sr. DevOps Engineer
201 East Fourth Street Cincinnati OH 45202
m: +1 719-393-5115
Dena.Bramhall@concentrix.com
www.concentrix.com<http://www.concentrix.com/>

**Comment by bariscaglar** [comment]
One reason I could find why people run into this issue is their Docker installation was set to "**Linux Containers**". 

That said, on my end, it all works:

docker pull mcr.microsoft.com/windows/servercore:1809
1809: Pulling from windows/servercore
65014b3c3121: Already exists                                                                                            02a4c14ecf32: Pull complete                                                                                             Digest: sha256:0193dba5d3c7f3c0e23ea956a62f77122585ddb2295435895ecc214122f47475
Status: Downloaded newer image for mcr.microsoft.com/windows/servercore:1809
mcr.microsoft.com/windows/servercore:1809

The rest of the output is similar. The diagnostics on your end could really help, unless @mamezgeb can see what's wrong from the version output above.

**Comment by dbramhallconcentrix** [comment]
I am set to windows containers because I am able to download other windows containers with different tags.

[CNX_logo_Color_SMALL]
Dena Bramhall | Sr. DevOps Engineer
201 East Fourth Street Cincinnati OH 45202
m: +1 719-393-5115
Dena.Bramhall@concentrix.com
www.concentrix.com<http://www.concentrix.com/>

**Comment by dbramhallconcentrix** [comment]
How do I run diagnostics while attempting to pull docker windows containers. There must be a specific setting docker desktop wants or an issue with my version of windows.

[CNX_logo_Color_SMALL]
Dena Bramhall | Sr. DevOps Engineer
201 East Fourth Street Cincinnati OH 45202
m: +1 719-393-5115
Dena.Bramhall@concentrix.com
www.concentrix.com<http://www.concentrix.com/>

**Comment by bariscaglar** [comment]
Could you be trying to pull versions that are higher than your OS version? Are the ones that work all lower version tags?

I think Rohit's original message contained the instructions on getting diagnostics: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-faq#enable-and-get-the-debug-logs-of-the-docker-daemon.

Also, your docker tooling version is old. Before proceeding, I suggest you upgrade to latest.

Finally, I think Markos was asking for the 'docker info'. What you pasted is 'docker version' output.

**Comment by dbramhallconcentrix** [comment]
Working on the other requests now.


PS C:\Windows\system32> docker info
Containers: 5
Running: 0
Paused: 0
Stopped: 5
Images: 13
Server Version: 18.09.2
Storage Driver: windowsfilter
Windows:
Logging Driver: json-file
Plugins:
Volume: local
Network: ics l2bridge l2tunnel nat null overlay transparent
Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Pro Version 1803 (OS Build 17134.885)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.9GiB
Name: WAH99DBRA9869
ID: VOU2:B4BD:V4NM:MWOJ:BXHK:TEEO:4NWN:MRFL:5C3W:U5JD:VV6Q:LJOW
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface

[CNX_logo_Color_SMALL]
Dena Bramhall | Sr. DevOps Engineer
201 East Fourth Street Cincinnati OH 45202
m: +1 719-393-5115
Dena.Bramhall@concentrix.com
www.concentrix.com<http://www.concentrix.com/>

**Comment by dbramhallconcentrix** [comment]
When you say docker tooling, do you mean my docker desktop version? I just tried to upgrade and docker responded by saying I was up to date.

[CNX_logo_Color_SMALL]
Dena Bramhall | Sr. DevOps Engineer
201 East Fourth Street Cincinnati OH 45202
m: +1 719-393-5115
Dena.Bramhall@concentrix.com
www.concentrix.com<http://www.concentrix.com/>

**Comment by bariscaglar** [comment]
> When you say docker tooling, do you mean my docker desktop version? I just tried to upgrade and docker responded by saying I was up to date.

You are actually quite right. You have the latest stable version. On my machine, I am on an "Edge Release", which is why my version is 19.xxxx while yours is 18.xxxx.

**Comment by bariscaglar** [comment]
> Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)

I think this is the reason why you are unable to pull 1809 images. This [StackOverflow](https://stackoverflow.com/questions/56475661/can-not-pull-nanoserver1903-docker-image) has a an answer to the issue similar to yours.

**Comment by dbramhallconcentrix** [comment]
I am at Windows version 1803. I am now downloading Windows Server core docker image with tag 1803. I’ll try with the Nano Server image once finished. Another quirk of Windows docker containers. 😊

[CNX_logo_Color_SMALL]
Dena Bramhall | Sr. DevOps Engineer
201 East Fourth Street Cincinnati OH 45202
m: +1 719-393-5115
Dena.Bramhall@concentrix.com
www.concentrix.com<http://www.concentrix.com/>

**Comment by bariscaglar** [comment]
Have you had success with 1803?

**Comment by dbramhallconcentrix** [comment]
Yes 1803 downloaded. Sorry, I am on multiple projects. I have it on my list to try the nanoserver tag first thing this evening.

[CNX_logo_Color_SMALL]
Dena Bramhall | Sr. DevOps Engineer
201 East Fourth Street Cincinnati OH 45202
m: +1 719-393-5115
Dena.Bramhall@concentrix.com
www.concentrix.com<http://www.concentrix.com/>

**Comment by bariscaglar** [comment]
Looks like this issue is resolved. Please feel free to reach out to us if you run into further problems.
