### ISSUE TITLE
Kubernetes cluster containers getting destroyed after migration to mcr.microsoft.com/dotnet/core/aspnet:3.1

### ISSUE THREAD

**Issue by ladlesshaikh** [microsoft/containerregistry#51]
With recent migration of our app from **microsoft/aspnetcore:2.0** to **mcr.microsoft.com/dotnet/core/aspnet:3.1**

We observed automatic decommission of the containers for minute or so and they getting restored, we are using nginx as the api gateway. And because of this outage we are getting increased 502 errors.

Everything was ok till the migration.

**Comment by bariscaglar** [comment]
hi @ladlesshaikh the behvaior you're observing is more likely to be a side affect of the actual dotnet image version increase than where you're pulling it from. Could you contact the dotnet team at https://github.com/dotnet/dotnet-docker and share your experience?
