### ISSUE TITLE
20H2 tags missing for windows/servercore/iis

### ISSUE THREAD

**Issue by jbiel** [microsoft/containerregistry#53]
We're updating our build pipelines to prep for 20H2 and found that the `windows/servercore/iis` repository has images tagged as `2009`, while all other repositories that we use are tagging as `20H2`. As far as I can tell, the `20H2` images in other repositories are the most updated ones and `20H2` is the preferred nomenclature.

**Comment by MichaelSimons** [comment]
cc @John-Hart

**Comment by John-Hart** [comment]
Thanks @jbiel.  I'm looking into this.  We had used 2009 as the base image so it's tagged the same.

**Comment by jbiel** [comment]
Thanks, I've been reading about this and the 2009 vs 20H2 situation is a bit of a mess. https://borncity.com/win/2020/10/18/windows-10-20h2-wie-heit-es-denn-nun-och-microsoft-einigt-euch/

**Comment by jbiel** [comment]
Hello, just wanted to check in to see if there's any kind of update on this. We're moving lots of our workloads over to Kubernetes and would like to have 20H2 images in place. Thanks!

**Comment by jbiel** [comment]
This seems to be remedied as the following tags are now in place. Closing issue.

```
20210413-windowsservercore-20H2
20210511-windowsservercore-20H2
windowsservercore-20H2
```
