### ISSUE TITLE
PS C:\Users\Administrator> docker pull mcr.microsoft.com/windows/servercore:ltsc1809

### ISSUE THREAD

**Issue by geajonesv** [microsoft/containerregistry#58]
I am trying to use docker run to download an image and get the error below
PS C:\Users\Administrator> docker pull mcr.microsoft.com/windows/servercore:ltsc1809
docker : Error response from daemon: Get https://mcr.microsoft.com/v2/: net/http: 
request canceled while waiting for connection (Client.Timeout exceeded while awaiting 
headers)

**Comment by bariscaglar** [comment]
Hi @geajonesv, there's no such tag for that image. The only ltsc tags for that specific image are:
    "ltsc2016",
    "ltsc2016-amd64",
    "ltsc2019",
    "ltsc2019-amd64",
    "ltsc2019_amd64"

You can see the available tags at https://mcr.microsoft.com/v2/windows/servercore/tags/list
