### ISSUE TITLE
Your build tool has a typo: rootfS

### ISSUE THREAD

**Issue by jonjohnsonjr** [microsoft/containerregistry#59]
Whatever is producing these images has a typo in the config file generation.

Looking at the config file for:
```
mcr.microsoft.com/windows/iotcore@sha256:e6c7080bf78f50b8382c5a30dab8ef51c6426004a9c1749136c11f507d503e76
```

```
$ curl -s -L https://mcr.microsoft.com/v2/windows/iotcore/blobs/sha256:5466c718be1bbae9580c4ff3f9adf2eb8282114b795cf51b09a2d69e9822aabd | jq . | grep root
  "rootfS": {
```

That `S` in `rootfS` is capitalized, but it should probably be `rootfs` per [the spec](https://github.com/opencontainers/image-spec/blob/269c1c5e1dca62a25c5fa94929776d758f5373ab/config.md#properties) and [specs-go](https://github.com/opencontainers/image-spec/blob/269c1c5e1dca62a25c5fa94929776d758f5373ab/specs-go/v1/config.go#L99).

As far as I know, this isn't a problem because most container runtimes are written in go, which has [case-insensitive json Unmarshalling](https://golang.org/pkg/encoding/json/#Unmarshal):

> To unmarshal JSON into a struct, Unmarshal matches incoming object keys to the keys used by Marshal (either the struct field name or its tag), preferring an exact match but also accepting a case-insensitive match.

In general, though, JSON _is_ case sensitive, so you're likely to run into issues with other languages.

**Comment by rcowsill** [comment]
I hit this issue working on `docker save` archive processing in [satackey/action-docker-layer-caching](https://github.com/satackey/action-docker-layer-caching).

It's on the backlog over at microsoft/Windows-Containers already, see: microsoft/Windows-Containers#107

**Comment by bariscaglar** [comment]
Sounds like Windows-Containers is already aware of this issue. Closing
