### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by MichaelSimons** [microsoft/containerregistry#6]
Copied from microsoft/dotnet-framework-docker#376 by @arnigunnar

I am trying to run this command ``docker pull mcr.microsoft.com/dotnet/framework/runtime:4.7.2-windowsservercore-ltsc2019``, but using the console, I always get an error. ``read tcp 10.44.103.63:59824->204.79.197.219:443: wsarecv: An existing connection was forcibly closed by the remote host.``. There are 4 layers to the image, and when I am running the command, it starts downloading all four, completes the last two, but the first two (1.408GB and 514MB) the console starts downloading a few times but always ends up failing.

I have tried building through VS2019 as well with a DOCKERFILE pointing to this image, that also fails.

Full results:
```
65014b3c3121: Downloading [==================================================>]  1.522GB/1.522GB
02a4c14ecf32: Downloading [==================================================>]  529.5MB/529.5MB
1477e74c02fd: Download complete
f5debc34d550: Download complete
read tcp 10.44.103.63:59910->204.79.197.219:443: wsarecv: An existing connection was forcibly closed by the remote host.
```

Does anyone have any suggestions for me?

**Comment by arnigunnar** [comment]
Tried different images, all with the same result:

```
microsoft/dotnet-framework-build:4.7.1-windowsservercore-ltsc2016
mcr.microsoft.com/dotnet/framework/samples:dotnetapp
mcr.microsoft.com/dotnet/framework/aspnet:3.5
```

**Comment by bariscaglar** [comment]
@MichaelSimons @arnigunnar are you still seeing the same issues? I tried all 4 mentioned images and they all pulled OK for me.

**Comment by MichaelSimons** [comment]
To be clear, I just copied this issue between repos on behalf of @arnigunnar.

**Comment by arnigunnar** [comment]
I tried on my home computer pulling the same image, and it seems to work fine for some reason. Have tried on my work computer in two different WiFi connections, but same result. Must be something on my computer that is doing this. This can be closed. Thanks for checking this out for me.

**Comment by bariscaglar** [comment]
Thanks for the confirmation, closing.
