### ISSUE TITLE
aqua scan reported an issue in mcr.microsoft.com/dotnet/sdk:5.0

### ISSUE THREAD

**Issue by mayasin-dev** [microsoft/containerregistry#64]
![image](https://user-images.githubusercontent.com/83573588/120322386-fb187600-c301-11eb-827e-d913f02e56c8.png)

**Comment by MichaelSimons** [comment]
@mayasin-dev, Any issues regarding the .NET images should be opened in https://github.com/dotnet/dotnet-docker/issues.

**Comment by mayasin-dev** [comment]
Thanks @MichaelSimons. Closed the review.
