### ISSUE TITLE
dotnet core images are not working after the update on 29.07 

### ISSUE THREAD

**Issue by ziadsa** [microsoft/containerregistry#73]
Since the images update yesterday, I cannot build any image for my code (.Net core 3.1). Error message and full logs can be found under my StackOverflow [question](https://stackoverflow.com/questions/68561615/ms-dotnet-core-container-images-are-cracked-error-ctc1014?noredirect=1#comment121171270_68561615)

Hope for quick help, since we are totally blocked in the project!

**Comment by qweeah** [comment]
Does it happens on Windows or WSL? Can you print the system time on your computer?

**Comment by ziadsa** [comment]
I working on Windows10, but I use Linux as target system for my docker images. 

Yes, I can print the system time, the .Net compiler works well on my machine, just pulling the base images is not working.

**Comment by ziadsa** [comment]
A Machine reboot was the solution. I just restarted my Windows machine and it works again!

**Comment by dhenriette** [comment]
> 

Doesn't work for me
