### ISSUE TITLE
MCR slow in South Africa

### ISSUE THREAD

**Issue by GertBurger** [microsoft/containerregistry#81]
Hi,

Pulling docker images from mcr seems to be much slower than from other locations. I rarely hit 10mbps and often its under 5mbps.
My fibre provider has decent peering in Western Europe and I can max out my line (200mbps) easily when fetching from other mirrors located in London for example.

As per the other tickets on this topic, here are some additional info that might be useful:
* Specific command was `docker pull mcr.microsoft.com/mssql/server`
* `curl https://mcr.microsoft.com/v2/mcr/hello-world/blobs/sha256:1b930d010525941c1d56ec53b97bd057a67ae1865eebf042686d2a2d18271ced` which returns the CDN host `northeurope.data.mcr.microsoft.com`
* `northeurope.data.mcr.microsoft.com` resolves to:
```
 northeurope.data.mcr.microsoft.com. 2676 IN CNAME northeurope-data-mcr-microsoft-com.a-0016.a-msedge.net.
northeurope-data-mcr-microsoft-com.a-0016.a-msedge.net.	240 IN CNAME a-0016.dc-msedge.net.
a-0016.dc-msedge.net.	239	IN	A	131.253.33.219
```
* Latency to `131.253.33.219` is 190msec over 22 hops.

Any chance of getting a mirror in the South Africa Azure region or just in Western Europe (London)?

**Comment by bariscaglar** [comment]
Hi @GertBurger, thanks for the additional data. We do have an MCR West Europe region. The Azure traffic manager redirection is based on performance of DNS servers in your vicinity so based on that information, it decides that North Europe is the best server for you, which is a decision we don't have control over. 

We admittedly have shortcomings in terms of performance in some parts of the world including South America, Africa and Asia. We have plans to add more endpoints in the future based on demand and I have taken note of yours. I'll keep this issue open along with others in the same vein.

**Comment by AndreHamilton-MSFT** [comment]
closing due to age
