### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by yatima1460** [microsoft/containerregistry#82]
`mcr.microsoft.com/dotnet/framework/sdk` works with a valid hash

```powershell
PS C:\Users\yatim> docker pull mcr.microsoft.com/dotnet/framework/sdk@sha256:c6e9c591b9e80e2cb0f8bcb736008ebbc3e3ed23de045523847ef0f9778dbaa6
mcr.microsoft.com/dotnet/framework/sdk@sha256:c6e9c591b9e80e2cb0f8bcb736008ebbc3e3ed23de045523847ef0f9778dbaa6: Pulling from dotnet/framework/sdk
Digest: sha256:c6e9c591b9e80e2cb0f8bcb736008ebbc3e3ed23de045523847ef0f9778dbaa6
Status: Image is up to date for mcr.microsoft.com/dotnet/framework/sdk@sha256:c6e9c591b9e80e2cb0f8bcb736008ebbc3e3ed23de045523847ef0f9778dbaa6
mcr.microsoft.com/dotnet/framework/sdk@sha256:c6e9c591b9e80e2cb0f8bcb736008ebbc3e3ed23de045523847ef0f9778dbaa6
```

`mcr.microsoft.com/windows/servercore` does not work with a valid hash

```powershell
PS C:\Users\yatim> docker pull mcr.microsoft.com/windows/servercore@sha256:d1724c2d9a8401aefd4dbf1af79904e2add6c9551cfdb55e2e7eec936b78ab91
Error response from daemon: received unexpected HTTP status: 500 Internal Server Error
```

Changing the hash to an invalid one returns

```powershell
PS C:\Users\yatim> docker pull mcr.microsoft.com/windows/servercore@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Error response from daemon: manifest for mcr.microsoft.com/windows/servercore@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa not found: manifest unknown: manifest sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa is not found
```

So there is a problem when the hash is valid and `mcr.microsoft.com/windows/servercore` is used

**Comment by qweeah** [comment]
@yatima1460 Thanks for reporting this issue. This is a known issue for OSS registries caused by descriptors ambiguity when Redis cache is used.

If you docker pull with an **existed** digest of a blob(e.g. config blob, layer blob), MCR will return:
- 500 if the blob is cached;
- 404 if the blob is not cached.

To avoid this issue, you can pull image with the image tag or manifest digest, which is also the proper way to use docker :)

**Comment by yatima1460** [comment]
> you can pull image with the image tag [...] which is also the proper way to use docker
I disagree, it's not the proper way to use docker, tags can be overwritten and change, sha256 is a good security measure

> manifest digest [...] which is also the proper way to use docker
Still got the 500 error

This is a very bad issue that needs to be fixed, it's basically impossible to use sha256 on GitHub Actions to build images that match the cached ones
