### ISSUE TITLE
6.0.0-rc.1 images are listed on the Dockerhub but they dont exist

### ISSUE THREAD

**Issue by MarioGK** [microsoft/containerregistry#83]
```
Error response from daemon: manifest for mcr.microsoft.com/dotnet/sdk:6.0.0-rc.1-bullseye-slim not found: manifest unknown: manifest tagged by "6.0.0-rc.1-bullseye-slim" is not found
```

Getting this error while trying to pull the image.

**Comment by mthalman** [comment]
That tag is not listed on Docker Hub for the [sdk](https://hub.docker.com/_/microsoft-dotnet-sdk) repository. I think you mean to be referencing `mcr.microsoft.com/dotnet/sdk:6.0.100-rc.1-bullseye-slim` instead.

**Comment by MarioGK** [comment]
Well at the time in the docker hub the image was 6.0.0 and not 6.0.100, well anyway changing it works

**Comment by mthalman** [comment]
You were probably looking at one of the runtime-related repositories such as [aspnet](https://hub.docker.com/_/microsoft-dotnet-aspnet). Runtime versions differ from SDK versions.

**Comment by mthalman** [comment]
See [Overview of how .NET is versioned](https://docs.microsoft.com/dotnet/core/versions/).
