### ISSUE TITLE
How to access MCR via Azure ER

### ISSUE THREAD

**Issue by edwardkuo** [microsoft/containerregistry#84]
Cloud we push images on MCR via azure express router?  I pull image and I got this message
 "Error initiating layer download: Get https://eastasia.data.mcr.microsoft.com/b29889755b1f4e46b6b44eb3182530c50joxcrfl25//docker/registry/v2/blobs/sha256/ef/ef11e3fc4f3c8fde075a1b6b355f949a4163916f4072d517d85436e89af06a04/data"

Or Azure express not support to pull MCR images?

**Comment by bariscaglar** [comment]
Hi, Express Route is a direct connection to Azure from your on-premise resources. The data layers are pulled from CDN providers worldwide. So the connection to eastasia.data.mcr.microsoft.com is not a connection to Azure. If you are within an environment that does not allow connections to IP addresses outside of Azure, the connection will not work.
