### ISSUE TITLE
How to query dotnet/aspnet tags?

### ISSUE THREAD

**Issue by GF-Huang** [microsoft/containerregistry#89]
`https://mcr.microsoft.com/v2/mcr/dotnet/aspnet/tags/list`

![image](https://user-images.githubusercontent.com/4510984/142128536-5a63fc9d-c34a-4f36-a5b9-69b48a4c5e9e.png)

**Comment by mthalman** [comment]
The correct URL is https://mcr.microsoft.com/v2/dotnet/aspnet/tags/list.

This link is provided on the [Docker Hub page](https://hub.docker.com/_/microsoft-dotnet-aspnet):
> You can retrieve a list of all available tags for dotnet/aspnet at https://mcr.microsoft.com/v2/dotnet/aspnet/tags/list

**Comment by mthalman** [comment]
> Yes, but I can't see 2.2 in that page, but in here: https://mcr.microsoft.com/v2/dotnet/core/aspnet/tags/list

That's right. That's also indicated on that same page:

> For tags contained in the old dotnet/core/aspnet repository, you can retrieve a list of those tags at https://mcr.microsoft.com/v2/dotnet/core/aspnet/tags/list.

This is related to https://github.com/dotnet/dotnet-docker/issues/2375. At the time the repo change occurred, .NET Core 2.2 was already EOL so those tags are not included in the new repos.
