### ISSUE TITLE
Need help with MCR webhook/testing (Microsoft internal team)

### ISSUE THREAD

**Issue by gauravIoTEdge** [microsoft/containerregistry#90]
Hi,

I’m exploring ideas to automate OS & framework patching for images [our releases](https://github.com/Azure/iotedge) depend on.
 
I’m trying to determine if it’s possible to trigger an AzureDevOps pipeline directly based on an image update in MCR. 

To test whether this is feasible or not, I’ll need to trigger some kind of an image update on MCR.

Do you have a test environment that I could use? My internal MSFT alias is **gakulkar**.

**Comment by terencet-dev** [comment]
Hi, my name is Terence and I am the PM for Microsoft Artifact Registry (also known as Microsoft Container Registry or MCR).

Closing this issue as this is older than six months. Please feel free to open another GitHub issue if this is not correctly resolved.
