### ISSUE TITLE
darwin/arm64 and darwin/amd64

### ISSUE THREAD

**Issue by gsmachado** [microsoft/containerregistry#91]
It would be nice if https://hub.docker.com/_/microsoft-dotnet-sdk/ and other containers in the Microsoft family also have the platforms `darwin/arm64` and `darwin/amd64`.

Then devs would be able to rely on, e.g., `mcr.microsoft.com/dotnet/sdk:6.0`, building images for `darwin/arm64`.

**Comment by AndreHamilton-MSFT** [comment]
Closing due to age. However dotnet sdk issues should be filed at https://github.com/dotnet/sdk/issues , where they would better be able to assist you
