### ISSUE TITLE
Lots of restarts and OOMKills on Azure Defender security-publisher pods

### ISSUE THREAD

**Issue by harrisonsp** [microsoft/containerregistry#93]
In my AKS cluster, I'm seeing lots of restarts and OOMKills for pods using the mcr.microsoft.com/azuredefender/stable/security-publisher:0.3.21 image. I'm not sure if this is the right place to ask for help with that (if not, please advise), but that seems like something that should not be happening.

![image](https://user-images.githubusercontent.com/15724435/147692260-10a862db-48cb-44e3-bf0f-4b8b15cd8ab2.png)

**Comment by AndreHamilton-MSFT** [comment]
closing due to age. For issues related to aks, please file on https://github.com/Azure/AKS
