### ISSUE TITLE
dotnet tests hanging when using sdk:6.0

### ISSUE THREAD

**Issue by owenashurst** [microsoft/containerregistry#95]
It seems like when using the `mcr.microsoft.com/dotnet/sdk:6.0` docker image, running the following command seems to hang
`dotnet test --test-adapter-path:. --logger:"junit;LogFileName=xunit/results.xml" --results-directory:test-results`

Seems fine when using .NET 5. All nuget packages have been updated when re-tasgeting .NET 6. I can confirm the build works on my windows machine in visual studio, and the tests run fine in the test explorer, but not in a container with this image.

**Comment by mthalman** [comment]
Since this is specific to the .NET container image and not the container registry, I suggest you instead log this at https://github.com/dotnet/dotnet-docker.
