### ISSUE TITLE
How to query the repository by paging?

### ISSUE THREAD

**Issue by chrisdaiii** [microsoft/containerregistry#96]
Is mcr.microsoft.com based on Registry V2 version? I found out that based on this documentation stating that pagination is not possible to fetch data.

GET /v2/_catalog?n=<n from the request>&last=<last repository value from previous response>

https://docs.docker.com/registry/spec/api/#listing-repositories

**Comment by AndreHamilton-MSFT** [comment]
As an optimization mar currently returns all results in the catalog without paginating the response. This may change in the future.
https://github.com/opencontainers/distribution-spec/blob/main/spec.md#api
