### ISSUE TITLE
multiple vulnerabilities in mcr.microsoft.com/dotnet/runtime-deps:2.1

### ISSUE THREAD

**Issue by jitendracodehacker** [microsoft/containerregistry#98]
There are multiple findings on mcr.microsoft.com/dotnet/runtime-deps:2.1 

![image](https://user-images.githubusercontent.com/25054529/151765530-5fe922ed-b236-445f-bc96-4ac09222b6f0.png)

i though of checking other image like alpine but i didnt found it .  Please guide me here

**Comment by mthalman** [comment]
This would be expected since [.NET Core 2.1 has been EOL since August 21, 2021](https://dotnet.microsoft.com/platform/support/policy/dotnet-core). Once a version is EOL, the associated container images are no longer kept up-to-date with patches.

**Comment by jitendracodehacker** [comment]
here i tried 3.1 also but they do have vulnerabilities. Could you suggest clean image for runtime-deps ?

**Comment by mthalman** [comment]
If you're concerned about getting a clean vulnerability scan, you're best bet is to use an image based on Alpine Linux, which [.NET does provide container images for](https://hub.docker.com/_/microsoft-dotnet). For Debian and Ubuntu, vulnerabilities showing up in scans is just a part of life. This is not specific to the .NET images. For example, the latest version of the base Debian 11 image currently shows [5 high criticality and 38 low criticality vulnerabilities from Snyk](https://snyk.io/advisor/docker/debian/bullseye).

**Comment by jitendracodehacker** [comment]
@mthalman  : thanks for support . I already tried alpine and stretch-slim but those also report vulnerabilities 
like for 2.1-alpine 
![image](https://user-images.githubusercontent.com/25054529/152480240-3b4f5908-bc01-42f3-b87e-5be83a53618e.png)

**Comment by mthalman** [comment]
Again, .NET Core 2.1 is EOL so there will most definitely be vulnerabilities in any 2.1 container images; they are not being maintained with the latest patches.
